---
kind: pipeline
type: docker
name: mold-bookdown

steps:
- name: build_test_image
  image: plugins/docker
  settings:
    username:
      from_secret: canister_username
    password:
      from_secret: canister_password
    repo: cloud.canister.io:5000/chazu/mold-bookdown
